### ISSUE TITLE
[Req 5} view individual staff details

### ISSUE THREAD

**Issue by odx-2020** [P5-9/ICT2201_P5-9_AY22-23_T1#26]
When displaying the staff availability, the workload assigned, staff’s job preference, staff’s
location at a particular date, and availabilities for the week should be shown.

**Comment by Tan-TeckLing** [comment]
Image showcasing the viewing of staff availability

![Image](https://user-images.githubusercontent.com/13763403/204096002-2536cd94-a8f7-44e4-8a03-c4ab9cf3c973.png)
