### ISSUE TITLE
[Req 6]  Manager to sort top 3 staff with lowest work load  + highlight staff with more than 40 hours

### ISSUE THREAD

**Issue by odx-2020** [P5-9/ICT2201_P5-9_AY22-23_T1#27]

**Comment by Tan-TeckLing** [comment]
Image showcasing sorted view of the most hours worked within the month

![Image](https://user-images.githubusercontent.com/13763403/204096347-265a7c45-36d8-4e39-8f1c-d7c04c768fb2.png)

Image showcasing sorted view of the least hours worked within the week

![Image](https://user-images.githubusercontent.com/13763403/204096403-5c3f126d-f76b-42ab-b230-e5944cd190fb.png)
