### ISSUE TITLE
[Req 9]  Staff to indicate job preference for the week

### ISSUE THREAD

**Issue by odx-2020** [P5-9/ICT2201_P5-9_AY22-23_T1#30]

**Comment by Pandaztea** [comment]
A preview of the staff job preference can be found in the screenshot below. More details can be found in the figma link that can be accessed from README.md.

![Image](https://user-images.githubusercontent.com/91119519/204097831-1366ef97-49ed-4323-afe0-3fbda53f79b2.png)



![Image](https://user-images.githubusercontent.com/91119519/204097854-339b1ca1-3629-494d-b27b-2869df89b1f9.png)
