### ISSUE TITLE
[Req 10] Staff can reject jobs + pop up to warn to discuss+ Manager to Approve request

### ISSUE THREAD

**Issue by odx-2020** [P5-9/ICT2201_P5-9_AY22-23_T1#31]

**Comment by Pandaztea** [comment]
Requirement 10 fulfilled in prototype, details can be accessed from the figma prototype located in README.md.

![Image](https://user-images.githubusercontent.com/91119519/204097989-8550053b-3436-4145-bafb-f6a410144aa2.png)



![Image](https://user-images.githubusercontent.com/91119519/204098002-05a0ed29-4e20-473a-bb2e-564573387734.png)



![Image](https://user-images.githubusercontent.com/91119519/204098032-9a03768a-edc1-447b-bbd0-f5a81ec7f64f.png)
