### ISSUE TITLE
Review and Edit M1 Report after Review

### ISSUE THREAD

**Issue by yoongyoung2001** [P5-9/ICT2201_P5-9_AY22-23_T1#34]
Edit the report after prof's comments and review

- [x] #37
- [x] #38
- [x] #39
- [x] #40
- [x] #41
- [x] #44 
- [x] #45 
- [x] #46 
- [x] #47 
- [x] #48

**Comment by odx-2020** [comment]
Completed sub-sections in our report and submitted on 29 October 2022.
