### ISSUE TITLE
Create Component Diagram

### ISSUE THREAD

**Issue by odx-2020** [P5-9/ICT2201_P5-9_AY22-23_T1#36]

**Comment by Tan-TeckLing** [comment]
Component Diagram was created in the link 
[](https://lucid.app/lucidchart/c87987ac-f0e4-4ec3-bd37-6010f381aaf7/edit?viewport_loc=43%2C206%2C1664%2C869%2C0_0&invitationId=inv_88ca688f-fc90-43c7-b524-82769ab73447)

**Comment by Tan-TeckLing** [comment]
Supposedly completed date: 29 October 2022
