### ISSUE TITLE
Update use case diagram

### ISSUE THREAD

**Issue by yoongyoung2001** [P5-9/ICT2201_P5-9_AY22-23_T1#37]

**Comment by odx-2020** [comment]
We are updating the changes for the report. 
-  Added Team Name 
-

**Comment by odx-2020** [comment]
1. Manager: 
Added Reassign Job

2. Staff:
Removed Generalisations

3. Added extends for accept/reject job

4. Created a Database Actor

**Comment by Pandaztea** [comment]
The team collaborated and updated the final version of use case diagram.
