### ISSUE TITLE
Update use case description

### ISSUE THREAD

**Issue by yoongyoung2001** [P5-9/ICT2201_P5-9_AY22-23_T1#38]
More details for some important use cases. And write alternative scenarios

**Comment by odx-2020** [comment]
Team - Use Case 1 & 2
Nhi - Use Cases 3,4,5
Teck Link - Use Cases 6,7,8
Olivia - Use Cases - 9,10,11
Serene  -Use Cases -12,13,14

**Comment by Pandaztea** [comment]
Team - Use Case 1 , 2, 15,16
Nhi - Use Cases 3,4,5
Teck Link - Use Cases 6,7,8
Olivia - Use Cases - 9,10,11
Serene -Use Cases -12,13,14
