### ISSUE TITLE
Redo estimation calculation (M1, 4.1)

### ISSUE THREAD

**Issue by yoongyoung2001** [P5-9/ICT2201_P5-9_AY22-23_T1#39]

**Comment by Pandaztea** [comment]
I have did the estimation calculation and effort estimation (hours)
[ICT2x01_M2__p5-9_ UCP.xlsx](https://github.com/P5-9/ICT2201_P5-9_AY22-23_T1/files/9894098/ICT2x01_M2__p5-9_.UCP.xlsx)
