### ISSUE TITLE
Update Architecture Diagram 

### ISSUE THREAD

**Issue by Pandaztea** [P5-9/ICT2201_P5-9_AY22-23_T1#47]

**Comment by Tan-TeckLing** [comment]
Architecture Diagram has been written and integrated into class diagram at
https://lucid.app/lucidchart/e87cb3c9-cb3f-4942-81ad-caec3c7e152a/edit?viewport_loc=-2630%2C-1706%2C6059%2C3164%2C0_0&invitationId=inv_5a1abc82-fea0-4b69-9192-2137a788754d
Completed date: 29 October 2022
