### ISSUE TITLE
Fix Requirements issues

### ISSUE THREAD

**Issue by Pandaztea** [P5-9/ICT2201_P5-9_AY22-23_T1#48]
- [x] fix PF7 (M1, 2.3)
- [x] Create more assumptions and dependencies (M1, 2.4)
- [x] update Functional requirements (M1, 3.2) :if staff miss deadline, can submit late request to inform manager their availability
- [x] fix FR11(M1, 3.2)
- [x] Create more Non-functional requirements (M1, 3.4)
- [x] fix PR1 to 3 sec(M1, 3.4.1)

**Comment by yoongyoung2001** [comment]
Updated according to the comment in M1 report

**Comment by yoongyoung2001** [comment]
Updated in the M2 report
