### ISSUE TITLE
Team Meeting: 25 October 9pm

### ISSUE THREAD

**Issue by yoongyoung2001** [P5-9/ICT2201_P5-9_AY22-23_T1#62]
Title: P5-9 Team Meeting
Present: Teck Ling, Olivia, Nhi, Serene
Time: 25 October 2022, Tuesday, 9:00PM - 11:15PM

Agenda:

- [x] Review Use Case Description and Use Case Diagram
- [x] Clarify with Prof on some of the requirements on Slack (Waiting for reply)
- [x] Discuss on diagram allocation 
- [x] Arrange for the next Team Meeting

**Comment by odx-2020** [comment]
Prof Serena has replied to our questions regarding 

1. PDPA
- Decision is to delete data after 6 months 

2. Job Preference 
- No preference Manager assigns all roles. The driver should assist / double up as care assistant 

3. Use Case for Late Submission 
- to be discussed as a team as to what we deem fit and whats reasonable.
