### ISSUE TITLE
[Application] Company Logo

### ISSUE THREAD

**Issue by Pandaztea** [P5-9/ICT2201_P5-9_AY22-23_T1#67]

**Comment by odx-2020** [comment]
The Logo we used throughout the System. 
![Image](https://user-images.githubusercontent.com/91136620/204091436-d400fdc4-ad01-4774-8f93-548100c5f6a3.png)

Serene and I helped to design this logo. 

Start Date  19 September 2022
End Date:  20 September 2022

**Comment by Pandaztea** [comment]
Yes we have made this nice logo
