### ISSUE TITLE
Update Gantt Chart for M3

### ISSUE THREAD

**Issue by odx-2020** [P5-9/ICT2201_P5-9_AY22-23_T1#75]
Update the process of testing stage and fix the number of tasks in WBS

**Comment by yoongyoung2001** [comment]
Adding main task Milestone 1 and Milestone 2 and move the subtasks accordingly
![image](https://user-images.githubusercontent.com/94042315/204092633-cb5c369f-6089-4cd3-a1b3-292d0e861acf.png)
Update testing process
![image](https://user-images.githubusercontent.com/94042315/204092653-fe26833b-bd2b-4272-a62b-87286a1594d9.png)
